### ISSUE TITLE
Importing excel file with fixed pane(s) results in an error

### ISSUE THREAD

**Issue by HurtzHurty** [nissl-lab/toxy#17]
Hello out there,   :)
trying to read a *.xls file with freezed pane(s) results in:

ICSharpCode.SharpZipLib.Zip.ZipException: 'Wrong Local header signature: 0xE011CFD0'

In detail:
ICSharpCode.SharpZipLib.Zip.ZipException
  HResult=0x80131600
  Message=Wrong Local header signature: 0xE011CFD0
  Source=ICSharpCode.SharpZipLib
  StackTrace:
   at ICSharpCode.SharpZipLib.Zip.ZipInputStream.GetNextEntry()
   at NPOI.OpenXml4Net.Util.ZipInputStreamZipEntrySource..ctor(ZipInputStream inp)
   at NPOI.OpenXml4Net.OPC.ZipPackage..ctor(Stream in1, PackageAccess access)
   at NPOI.OpenXml4Net.OPC.OPCPackage.Open(Stream in1)
   at NPOI.Util.PackageHelper.Open(Stream is1)
   at NPOI.XSSF.UserModel.XSSFWorkbook..ctor(Stream is1)
   at Exel_with_NAPI.Form1.Form1_Load(Object sender, EventArgs e) in K:\Projects\Software\Software Test\Excel with Napi\Exel with NAPI\Form1.vb:line 28
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

It would be nice to be able to import fixed panes or that they are unfixed.
People always forget unfixing before saving.

Have a sunny weekend ...

**Comment by tonyqus** [comment]
This looks to be a fake xlsx file. The file header is incorrect. Can you double check if this is a html/xls file with notepad++ or some other file editor?
