### ISSUE TITLE
RTF files extraction support

### ISSUE THREAD

**Issue by ZedZipDev** [nissl-lab/toxy#22]
It was removed and I cannot find how to parse RTF files. Is it possible?

**Comment by tonyqus** [comment]
Yes, it's removed from .net core version since I don't find a good library on .NET core to parse it.  Give me some time to find a new RTF library on .NET core.

**Comment by Oleg26Dev** [comment]
Yes, I understand. The RTF format is a "wild" ;-). Btw, I have used some code in my SQLCLR function to parse rtf ; rtf in -> pure text out. Finally it works fine. I can share it .

**Comment by tonyqus** [comment]
I'm reviewing RockNHawk's code of RTFTextParser
https://github.com/RockNHawk/Toxy.NetCore/blob/netcore/ToxyFramework/Parsers/RTFTextParser.cs

Do you think this ToHtml method can meet your need?

**Comment by Oleg26Dev** [comment]
Probably it is what I need but:
I have created a small test app and tried to parse rtf files from your \testdata folder.
```
        static void TestParseRTFFromSample1()
        {
            string path = HelperClass.GetRTFPath("Blank.rtf");// ("htmlrtf1.rtf");// ("Simple text.rtf");
            var parser = new RTFTextParser(new ParserContext(path));
            string result = parser.Parse();//<-----------error is here
            Console.WriteLine("Result:{0}", result);
        }
```
```
public override string Parse()
        {
            using (var fs = new FileStream(Context.Path, FileMode.Open))
            {
                var html = Rtf.ToHtml(fs);//<---------
                return html;
            }
        }

```
The exception text:
```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'RtfPipe.TextEncoding' threw an exception.
  Source=RtfPipe
  StackTrace:
   at RtfPipe.TextEncoding.get_RtfDefault()
   at RtfPipe.RtfStreamReader..ctor(Stream stream, Int32 bufferSize)
   at RtfPipe.RtfStreamReader..ctor(Stream stream)
   at RtfPipe.RtfSource.op_Implicit(Stream value)
   at Toxy.Parsers.RTFTextParser.Parse() in D:\MyProjects3\NET\Toxy.NetCore-netcore\ToxyFramework\Parsers\RTFTextParser.cs:line 20
   at ConsoleApp1.Program.TestParseRTFFromSample1() in D:\MyProjects3\NET\Toxy.NetCore-netcore\ConsoleApp1\Program.cs:line 21
   at ConsoleApp1.Program.Main(String[] args) in D:\MyProjects3\NET\Toxy.NetCore-netcore\ConsoleApp1\Program.cs:line 13

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ArgumentException: 'Windows-1252' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')


```

**Comment by Oleg26Dev** [comment]
And note: to replace using iFilter  the RTF parser should work ;-)

**Comment by tonyqus** [comment]
Your requirement makes sense. I also have concerns on RTFPipe. The extracted html result is not what most users need.

**Comment by Oleg26Dev** [comment]
By the way, I have tested and this recommendation works fine:

https://stackoverflow.com/questions/46119392/how-do-i-convert-an-rtf-string-to-a-markdown-string-and-back-c-net-core-or/54755138#54755138

It really extracts pure text from RTF file.

**Comment by Oleg26Dev** [comment]
Can you add this (BracketPipe-like, see the previous link) implementation to your framework?

**Comment by tonyqus** [comment]
I still have some concern on this method. It converts RTF to HTML and then convert HTML to markdown but it's still not plain text.

**Comment by tonyqus** [comment]
English extraction works but something wrong with far-east character (e.g. Chinese) extraction

**Comment by Flamifly** [comment]
I opened a PR with a working port of the ReasonableRTF Library in .Net Standard 2.1

The Test for Chinese Charakters was successfully.

**Comment by tonyqus** [comment]
While reviewing the code of RTFTextParser, I notice that it has to use byte array to finish the conversion instead of stream based. This can cause unnecessary memory consumption

**Comment by tonyqus** [comment]
Nice to see you here. Since Toxy is not used widely so far, performance is not the top priority we should consider. 

I agree that RTF files shouldn't be so huge. If it's a book with hundreds of pages, usually people are willing to use PDF or epub.
